"""Port: ILLMClient — abstract interface for LLM text generation."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import AsyncIterator


class ILLMClient(ABC):
    """
    Defines the contract for streaming LLM text generation.

    The concrete adapter (FoundryLLMAdapter) calls the OpenAI-compatible
    Foundry Local API. Any future adapter (e.g., OpenAI cloud, Ollama)
    implements this interface without changing the use case.
    """

    @abstractmethod
    async def stream(
        self,
        system_prompt: str,
        user_prompt: str,
        expected_days: int | None = None,
        json_schema: dict | None = None,
    ) -> AsyncIterator[str]:
        """
        Yield text tokens as they are generated by the model.

        Args:
            system_prompt: Instruction context for the model.
            user_prompt:   The user's specific request (RAG-augmented).
            expected_days: Beklenen gün sayısı. Adapter token bütçesini
                buna göre ölçekler; None ise taban bütçe kullanılır.

        Yields:
            Raw token strings in generation order.
        """
        ...  # pragma: no cover

    @abstractmethod
    async def health_check(self) -> bool:
        """Returns True if the LLM service is reachable and responsive."""
        ...  # pragma: no cover

    @property
    @abstractmethod
    def model_name(self) -> str:
        """The identifier of the currently loaded model."""
        ...  # pragma: no cover
