"""
Domain models: Itinerary and its constituent parts.

Zero external dependencies — stdlib only.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime

from backend.domain.models.trip_request import BudgetLevel, TripRequest


@dataclass
class ActivityBlock:
    """A single time-slot activity (morning, afternoon, or evening)."""

    description: str
    location: str = ""
    why_recommended: str = ""
    duration_estimate: str = ""
    cost_estimate: str = ""
    reservation_needed: bool = False
    transport_suggestion: str = ""
    lat: float | None = None
    lon: float | None = None


@dataclass
class MealSuggestion:
    breakfast: str = ""
    lunch: str = ""
    dinner: str = ""


@dataclass
class Day:
    """One day of the itinerary."""

    day_number: int
    title: str
    morning: ActivityBlock
    afternoon: ActivityBlock
    evening: ActivityBlock
    meals: MealSuggestion
    budget_estimate: BudgetLevel
    tips: list[str] = field(default_factory=list)


@dataclass
class Itinerary:
    """Complete travel itinerary generated by the AI pipeline."""

    trip_request: TripRequest
    days: list[Day]
    model_used: str
    created_at: datetime = field(default_factory=datetime.utcnow)
    id: str = ""                    # Assigned by repository on save
    raw_response: str = ""          # Stored for debugging / re-parsing
    kb_miss: bool = False           # True → KB had no chunks for this city;
                                    # plan used general LLM knowledge only.
                                    # Persisted so the badge is accurate on
                                    # history re-opens, not just during generation.
    is_favorite: bool = False       # True → User marked this itinerary as favorite.
    constraint_score: float = 1.0   # 0.0 to 1.0 score from Python Validator
    quality_score: float = 1.0      # 0.0 to 1.0 soft metrics score from Python Validator

    @property
    def destinations(self) -> tuple[str, ...]:
        return self.trip_request.destinations

    @property
    def destination(self) -> str:
        return ", ".join(self.trip_request.destinations)

    @property
    def duration_days(self) -> int:
        return self.trip_request.duration_days

    def is_complete(self) -> bool:
        """Returns True if all expected days were successfully parsed."""
        return len(self.days) == self.trip_request.duration_days


@dataclass
class ItinerarySummary:
    """Lightweight projection for list views — avoids loading full day data."""

    id: str
    destination: str
    duration_days: int
    budget: BudgetLevel
    model_used: str
    created_at: datetime
    day_count: int
    is_favorite: bool = False
